config/routes.rb
Weather::Application.routes.draw do
  resources :cities, only: :index do
    resource :condition, only: :show
  end

  root 'cities#index'

  

end

app/models/city.rb
class City < ActiveRecord::Base
  validates_presence_of :name, :woeid

  def condition
    @condition ||= Condition.new(self)
  end
end

app/models/condition.rb
class Condition
  include HTTParty

  base_uri 'http://weather.yahooapis.com'
  format :xml
  default_params u: :c

  attr_reader :city

  def initialize(city)
    @city = city
  end

  delegate :woeid, :name, to: :city

  def temperature
    condition['temp'].to_f
  end

  def description
    condition['text']
  end

  def code
    condition['code'].to_i
  end

  def latitude
    item['lat'].to_f
  end

  def longitude
    item['long'].to_f
  end

  private

  def item
    response['rss']['channel']['item']
  end

  def condition
    item['condition']
  end

  def response
    @response ||= self.class.get('/forecastrss', query: { w: woeid })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
    respond_to do |format|
      format.html
      format.json { render json: @cities }
    end
  end
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_city

  def show
    @condition = @city.condition
  end

  protected

  def set_city
    @city = City.find(params[:city_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_time
    Time.now.asctime
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
  def format_temperature_for(condition)
    '%.1f' % condition.temperature
  end

  def condition_tag_for(condition, &block)
    content_tag(:dl, class: condition_class_for(condition), &block)
  end

  def condition_class_for(condition)
    'code-%d' % condition.code
  end

  def google_maps_javascript_include_tag
    javascript_include_tag google_maps_source
  end

  def google_maps_source
    'https://maps.googleapis.com/maps/api/js?key=%s&sensor=true' % google_maps_api_key
  end

  def google_maps_api_key
    ENV['GOOGLE_MAPS_API_KEY']
  end

  def map_tag_for(condition)
    content_tag :div, '', id: 'map-canvas', data: data_for(condition)
  end

  def data_for(condition)
    { latitude: condition.latitude, longitude: condition.longitude }
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def format_temperature(value)
    '%.1f' % value
  end
end

app/views/application/_footer.html.erb
<footer role='contentinfo'>
  <time><%= current_time %></time>
  <p>Learn &#38; discuss Ruby at <%= link_to 'Ruby Meetups Montevideo', 'http://www.meetup.com/rubymvd/' %></p>
</footer>

app/views/application/_header.html.erb
<header role='banner'>
  <%= link_to '/', :class => 'brand' do %>
    Ruby Weather
  <% end %>
  <%= link_to 'http://www.meetup.com/rubymvd/', :class => 'meetup', :rel => 'external' do %>
    <%= image_tag 'ruby-meetups.png' %>
  <% end %>
</header>

app/views/cities/index.html.erb
<main id='cities' role='main'>
  <h1>Choose a city and get today&#8217;s weather!</h1>
  <ul id='cities-list'>
    <% @cities.each do |city| %>
      <li><%= link_to city.name, city_condition_path(city) %></li>
    <% end %>
  </ul>
</main>

app/views/conditions/_forecast.html.erb
<div class='forecast <%= 'hide' if forecast_counter != 0 %>' data-index='<%= forecast_counter %>'>
  <h2 class='forecast-day-title'> <%= forecast['day'] %> <%= forecast['date'] %></h2>
  <h2 class='forecast-high-low'>L <%= forecast['low'] %> / M <%= forecast ['high'] %></h2>
</div>

app/views/conditions/show.html.erb
<main id='city-conditions' role='main'>
  <h1>Current weather conditions for <%= @condition.name %></h1>
  <%= condition_tag_for(@condition) do %>
    <dt>Temperature</dt>
    <dd><%= format_temperature_for @condition %></dd>
    <dt>Condition</dt>
    <dd><%= @condition.description %></dd>
  <% end %>
  <%= map_tag_for @condition %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= google_maps_javascript_include_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'header' %>
  <%= yield %>
</body>
</html>

app/views/welcome/index.html.erb
<p>
  Current weather conditions for Montevideo:
</p>
<dl>
  <dt>Temperature</dt>
  <dd><%= format_temperature @condition.temperature %></dd>
  <dt>Condition</dt>
  <dd><%= @condition.description %></dd>
</dl>